export const currencyToCountryCode: Record<string, string> = {
    PLN: 'pl',
    USD: 'us',
    EUR: 'eu',
    GBP: 'gb',
    CHF: 'ch',
    AUD: 'au',
    CAD: 'ca',
    NOK: 'no',
    SEK: 'se',
    DKK: 'dk',
    CZK: 'cz',
    JPY: 'jp',
    HUF: 'hu',
    TRY: 'tr',
    BGN: 'bg',
    CNY: 'cn',
    HRK: 'hr',
    MXN: 'mx',
    ZAR: 'za',
    NZD: 'nz',
    BRL: 'br',
    ILS: 'il',
    RUB: 'ru',
    MYR: 'my',
    IDR: 'id',
    INR: 'in',
    KRW: 'kr',
    PHP: 'ph',
    SGD: 'sg',
    THB: 'th',

};